const ProductMessage = {
    ADD_PROUDCT_FAIL: ,
    ADD_PRODUCT_SUCCESS: ,
    EDIT_PROUDCT_FAIL: ,
    EDIT_PRODUCT_SUCCESS: ,
    REMOVE_PRODUCT_FAIL: ,
    REMOVE_PRODUCT_SUCCESS: ,
    PRODUC_NOT_FOUND: ,
}
const CourseMessage = {
    ADD_COURSE_FAIL: ,
    ADD_COURSE_SUCCESS: ,
    EDIT_COURSE_FAIL: ,
    EDIT_COURSE_SUCCESS: ,
    REMOVE_COURSE_FAIL: ,
    REMOVE_COURSE_SUCCESS: ,
    COURSE_NOT_FOUND: 
}

const BlogMessage = {
    ADD_BLOG_FAIL: ,
    ADD_BLOG_SUCCESS: ,
    EDIT_BLOG_FAIL: ,
    EDIT_BLOG_SUCCESS: ,
    REMOVE_BLOG_FAIL: ,
    REMOVE_BLOG_SUCCESS: ,
    BLOG_NOT_FOUND:
}

const categoryMessage = {
    ADD_CATEGORY_FAIL: ,
    ADD_CATEGORY_SUCCESS: ,
    EDIT_CATEGORY_FAIL: ,
    EDIT_CATEGORY_SUCCESS: ,
    REMOVE_CATEGORY_FAIL: ,
    REMOVE_CATEGORY_SUCCESS: ,
    CATEGORY_NOT_FOUND: ,
}

const EpisodeMessage = {
    ADD_EPISODE_FAIL: ,
    ADD_EPISODE_SUCCESS: ,
    EDIT_EPISODE_FAIL: ,
    EDIT_EPISODE_SUCCESS: ,
    REMOVE_EPISODE_FAIL: ,
    REMOVE_EPISODE_SUCCESS: ,
    EPISODE_NOT_FOUND: ,
}

const ChapterMessage = {
    ADD_CHAPTER_FAIL: ,
    ADD_CHAPTER_SUCCESS: ,
    EDIT_CHAPTER_FAIL: ,
    EDIT_CHAPTER_SUCCESS: ,
    REMOVE_CHAPTER_FAIL: ,
    REMOVE_CHAPTER_SUCCESS: ,
    CHAPTER_NOT_FOUND: 
}

const UserMessage = {
    ADD_USER_FAIL: ,
    ADD_USER_SUCCESS: ,
    EDIT_USER_FAIL: ,
    EDIT_USER_SUCCESS: ,
    REMOVE_USER_FAIL: ,
    REMOVE_USER_SUCCESS: ,
    USER_NOT_FOUND
}

const AuthMessage = {
    UNAUTHORIZED:,
    SEND_CODE_SUCCESS: ,
    NOT_FOUND_USER_WITH_PHONE_NUMBER:,
    INVALID_CODE: ,
    CODE_EXPIRES: ,
}
const TokenMessage = {
    SIGN_IN: ,
    ACCOUNT_NOT_FOUND: ,
}